server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(glb|gltf|wasm|ico|svg|png|jpg|jpeg|webp|woff2?)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
