#!/usr/bin/env bash
# Ensure nakanaori-kebbi/local.properties exists (sdk.dir for Gradle).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
KEBBI="${NAKANAORI_KEBBI_ROOT:-$ROOT/../nakanaori-kebbi}"
LOCAL="$KEBBI/local.properties"

if [[ -f "$LOCAL" ]]; then
  exit 0
fi

sdk=""
if [[ -n "${ANDROID_HOME:-}" && -d "$ANDROID_HOME" ]]; then
  sdk="$ANDROID_HOME"
elif [[ -n "${ANDROID_SDK_ROOT:-}" && -d "$ANDROID_SDK_ROOT" ]]; then
  sdk="$ANDROID_SDK_ROOT"
elif [[ -d "$HOME/Library/Android/sdk" ]]; then
  sdk="$HOME/Library/Android/sdk"
fi

if [[ -z "$sdk" ]]; then
  CHARATOMO_LOCAL="$ROOT/../AIxR-CharaTomo-Kebbi/local.properties"
  if [[ -f "$CHARATOMO_LOCAL" ]]; then
    sdk="$(grep -E '^sdk\.dir=' "$CHARATOMO_LOCAL" | cut -d= -f2- | tr -d '\r')"
  fi
fi

if [[ -z "$sdk" || ! -d "$sdk" ]]; then
  echo "[kebbi-ensure-sdk] ERROR: Android SDK not found." >&2
  echo "Set ANDROID_HOME or create $LOCAL with sdk.dir=..." >&2
  echo "Example: cp $KEBBI/local.properties.example $LOCAL" >&2
  exit 1
fi

mkdir -p "$(dirname "$LOCAL")"
cat >"$LOCAL" <<EOF
## Auto-generated by scripts/kebbi-ensure-sdk.sh — do not commit
sdk.dir=$sdk
EOF
echo "[kebbi-ensure-sdk] wrote $LOCAL (sdk.dir=$sdk)"
